export const PROGRAMS = [
  '── Credit Cards ──', 'Capital One', 'Chase', 'Amex', 'Citi',
  '── Airlines ──', 'ANA Mileage Club', 'Air Canada Aeroplan', 'Virgin Atlantic Flying Club', 'Turkish Miles&Smiles', 'Delta Skymiles', 'United MileagePlus', 'AA AAdvantage', 'Southwest Rapid Rewards', 'Flying Blue', 'AeroMexico', 'Alaska Mileage Plan', 'JetBlue TrueBlue',
  '── Hotels ──', 'Marriott Bonvoy', 'Hilton Honors', 'Hyatt', 'IHG One Rewards', 'Wyndham', 'Choice',
  '── Car Rentals ──', 'Hertz', 'National', 'Enterprise', 'Avis',
  '── Travel Platforms ──', 'Viator', 'Expedia', 'hotels.com', 'VRBO', 'booking.com', 'Priceline', 'Orbitz', 'trip.com', 'AirBnB',
  '── Cruises ──', 'Carnival', 'Royal Caribbean', 'Norwegian', 'Disney Cruise', 'Princess', 'Celebrity',
  '── Other ──', 'Priority Pass', 'Other'
];

export const COUNTRIES = [
  { name: 'United States', code: 'US', currency: 'US Dollar', currencyCode: 'USD' },
  { name: 'Japan', code: 'JP', currency: 'Japanese Yen', currencyCode: 'JPY' },
  { name: 'United Kingdom', code: 'GB', currency: 'British Pound', currencyCode: 'GBP' },
  { name: 'European Union', code: 'EU', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Canada', code: 'CA', currency: 'Canadian Dollar', currencyCode: 'CAD' },
  { name: 'Australia', code: 'AU', currency: 'Australian Dollar', currencyCode: 'AUD' },
  { name: 'Mexico', code: 'MX', currency: 'Mexican Peso', currencyCode: 'MXN' },
  { name: 'Costa Rica', code: 'CR', currency: 'Costa Rican Colón', currencyCode: 'CRC' },
  { name: 'France', code: 'FR', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Germany', code: 'DE', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Italy', code: 'IT', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Spain', code: 'ES', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Portugal', code: 'PT', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Greece', code: 'GR', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Netherlands', code: 'NL', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Switzerland', code: 'CH', currency: 'Swiss Franc', currencyCode: 'CHF' },
  { name: 'Norway', code: 'NO', currency: 'Norwegian Krone', currencyCode: 'NOK' },
  { name: 'Sweden', code: 'SE', currency: 'Swedish Krona', currencyCode: 'SEK' },
  { name: 'Denmark', code: 'DK', currency: 'Danish Krone', currencyCode: 'DKK' },
  { name: 'Iceland', code: 'IS', currency: 'Icelandic Króna', currencyCode: 'ISK' },
  { name: 'Ireland', code: 'IE', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Austria', code: 'AT', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Belgium', code: 'BE', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Czech Republic', code: 'CZ', currency: 'Czech Koruna', currencyCode: 'CZK' },
  { name: 'Poland', code: 'PL', currency: 'Polish Złoty', currencyCode: 'PLN' },
  { name: 'Hungary', code: 'HU', currency: 'Hungarian Forint', currencyCode: 'HUF' },
  { name: 'Croatia', code: 'HR', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Turkey', code: 'TR', currency: 'Turkish Lira', currencyCode: 'TRY' },
  { name: 'Israel', code: 'IL', currency: 'Israeli Shekel', currencyCode: 'ILS' },
  { name: 'United Arab Emirates', code: 'AE', currency: 'UAE Dirham', currencyCode: 'AED' },
  { name: 'Saudi Arabia', code: 'SA', currency: 'Saudi Riyal', currencyCode: 'SAR' },
  { name: 'India', code: 'IN', currency: 'Indian Rupee', currencyCode: 'INR' },
  { name: 'China', code: 'CN', currency: 'Chinese Yuan', currencyCode: 'CNY' },
  { name: 'South Korea', code: 'KR', currency: 'South Korean Won', currencyCode: 'KRW' },
  { name: 'Thailand', code: 'TH', currency: 'Thai Baht', currencyCode: 'THB' },
  { name: 'Vietnam', code: 'VN', currency: 'Vietnamese Dong', currencyCode: 'VND' },
  { name: 'Indonesia', code: 'ID', currency: 'Indonesian Rupiah', currencyCode: 'IDR' },
  { name: 'Singapore', code: 'SG', currency: 'Singapore Dollar', currencyCode: 'SGD' },
  { name: 'Malaysia', code: 'MY', currency: 'Malaysian Ringgit', currencyCode: 'MYR' },
  { name: 'Philippines', code: 'PH', currency: 'Philippine Peso', currencyCode: 'PHP' },
  { name: 'Hong Kong', code: 'HK', currency: 'Hong Kong Dollar', currencyCode: 'HKD' },
  { name: 'Taiwan', code: 'TW', currency: 'New Taiwan Dollar', currencyCode: 'TWD' },
  { name: 'New Zealand', code: 'NZ', currency: 'New Zealand Dollar', currencyCode: 'NZD' },
  { name: 'Brazil', code: 'BR', currency: 'Brazilian Real', currencyCode: 'BRL' },
  { name: 'Argentina', code: 'AR', currency: 'Argentine Peso', currencyCode: 'ARS' },
  { name: 'Chile', code: 'CL', currency: 'Chilean Peso', currencyCode: 'CLP' },
  { name: 'Colombia', code: 'CO', currency: 'Colombian Peso', currencyCode: 'COP' },
  { name: 'Peru', code: 'PE', currency: 'Peruvian Sol', currencyCode: 'PEN' },
  { name: 'Panama', code: 'PA', currency: 'Panamanian Balboa', currencyCode: 'PAB' },
  { name: 'Belize', code: 'BZ', currency: 'Belize Dollar', currencyCode: 'BZD' },
  { name: 'Guatemala', code: 'GT', currency: 'Guatemalan Quetzal', currencyCode: 'GTQ' },
  { name: 'Honduras', code: 'HN', currency: 'Honduran Lempira', currencyCode: 'HNL' },
  { name: 'Nicaragua', code: 'NI', currency: 'Nicaraguan Córdoba', currencyCode: 'NIO' },
  { name: 'El Salvador', code: 'SV', currency: 'US Dollar', currencyCode: 'USD' },
  { name: 'Dominican Republic', code: 'DO', currency: 'Dominican Peso', currencyCode: 'DOP' },
  { name: 'Cuba', code: 'CU', currency: 'Cuban Peso', currencyCode: 'CUP' },
  { name: 'Jamaica', code: 'JM', currency: 'Jamaican Dollar', currencyCode: 'JMD' },
  { name: 'Bahamas', code: 'BS', currency: 'Bahamian Dollar', currencyCode: 'BSD' },
  { name: 'Cayman Islands', code: 'KY', currency: 'Cayman Islands Dollar', currencyCode: 'KYD' },
  { name: 'Turks and Caicos', code: 'TC', currency: 'US Dollar', currencyCode: 'USD' },
  { name: 'Puerto Rico', code: 'PR', currency: 'US Dollar', currencyCode: 'USD' },
  { name: 'Egypt', code: 'EG', currency: 'Egyptian Pound', currencyCode: 'EGP' },
  { name: 'Morocco', code: 'MA', currency: 'Moroccan Dirham', currencyCode: 'MAD' },
  { name: 'South Africa', code: 'ZA', currency: 'South African Rand', currencyCode: 'ZAR' },
  { name: 'Kenya', code: 'KE', currency: 'Kenyan Shilling', currencyCode: 'KES' },
  { name: 'Tanzania', code: 'TZ', currency: 'Tanzanian Shilling', currencyCode: 'TZS' },
  { name: 'Ghana', code: 'GH', currency: 'Ghanaian Cedi', currencyCode: 'GHS' },
  { name: 'Nigeria', code: 'NG', currency: 'Nigerian Naira', currencyCode: 'NGN' },
  { name: 'Russia', code: 'RU', currency: 'Russian Ruble', currencyCode: 'RUB' },
  { name: 'Ukraine', code: 'UA', currency: 'Ukrainian Hryvnia', currencyCode: 'UAH' },
  { name: 'Romania', code: 'RO', currency: 'Romanian Leu', currencyCode: 'RON' },
  { name: 'Bulgaria', code: 'BG', currency: 'Bulgarian Lev', currencyCode: 'BGN' },
  { name: 'Serbia', code: 'RS', currency: 'Serbian Dinar', currencyCode: 'RSD' },
  { name: 'Albania', code: 'AL', currency: 'Albanian Lek', currencyCode: 'ALL' },
  { name: 'North Macedonia', code: 'MK', currency: 'Macedonian Denar', currencyCode: 'MKD' },
  { name: 'Bosnia and Herzegovina', code: 'BA', currency: 'Bosnia-Herzegovina Convertible Mark', currencyCode: 'BAM' },
  { name: 'Montenegro', code: 'ME', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Slovenia', code: 'SI', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Slovakia', code: 'SK', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Lithuania', code: 'LT', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Latvia', code: 'LV', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Estonia', code: 'EE', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Finland', code: 'FI', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Luxembourg', code: 'LU', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Malta', code: 'MT', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Cyprus', code: 'CY', currency: 'Euro', currencyCode: 'EUR' },
  { name: 'Maldives', code: 'MV', currency: 'Maldivian Rufiyaa', currencyCode: 'MVR' },
  { name: 'Sri Lanka', code: 'LK', currency: 'Sri Lankan Rupee', currencyCode: 'LKR' },
  { name: 'Nepal', code: 'NP', currency: 'Nepalese Rupee', currencyCode: 'NPR' },
  { name: 'Pakistan', code: 'PK', currency: 'Pakistani Rupee', currencyCode: 'PKR' },
  { name: 'Bangladesh', code: 'BD', currency: 'Bangladeshi Taka', currencyCode: 'BDT' },
  { name: 'Myanmar', code: 'MM', currency: 'Myanmar Kyat', currencyCode: 'MMK' },
  { name: 'Cambodia', code: 'KH', currency: 'Cambodian Riel', currencyCode: 'KHR' },
  { name: 'Laos', code: 'LA', currency: 'Lao Kip', currencyCode: 'LAK' },
  { name: 'Mongolia', code: 'MN', currency: 'Mongolian Tögrög', currencyCode: 'MNT' },
  { name: 'Kazakhstan', code: 'KZ', currency: 'Kazakhstani Tenge', currencyCode: 'KZT' },
  { name: 'Uzbekistan', code: 'UZ', currency: 'Uzbekistani Som', currencyCode: 'UZS' },
  { name: 'Georgia', code: 'GE', currency: 'Georgian Lari', currencyCode: 'GEL' },
  { name: 'Armenia', code: 'AM', currency: 'Armenian Dram', currencyCode: 'AMD' },
  { name: 'Azerbaijan', code: 'AZ', currency: 'Azerbaijani Manat', currencyCode: 'AZN' },
  { name: 'Jordan', code: 'JO', currency: 'Jordanian Dinar', currencyCode: 'JOD' },
  { name: 'Lebanon', code: 'LB', currency: 'Lebanese Pound', currencyCode: 'LBP' },
  { name: 'Qatar', code: 'QA', currency: 'Qatari Riyal', currencyCode: 'QAR' },
  { name: 'Kuwait', code: 'KW', currency: 'Kuwaiti Dinar', currencyCode: 'KWD' },
  { name: 'Bahrain', code: 'BH', currency: 'Bahraini Dinar', currencyCode: 'BHD' },
  { name: 'Oman', code: 'OM', currency: 'Omani Rial', currencyCode: 'OMR' },
  { name: 'Ethiopia', code: 'ET', currency: 'Ethiopian Birr', currencyCode: 'ETB' },
  { name: 'Uganda', code: 'UG', currency: 'Ugandan Shilling', currencyCode: 'UGX' },
  { name: 'Rwanda', code: 'RW', currency: 'Rwandan Franc', currencyCode: 'RWF' },
  { name: 'Zambia', code: 'ZM', currency: 'Zambian Kwacha', currencyCode: 'ZMW' },
  { name: 'Zimbabwe', code: 'ZW', currency: 'US Dollar', currencyCode: 'USD' },
  { name: 'Botswana', code: 'BW', currency: 'Botswana Pula', currencyCode: 'BWP' },
  { name: 'Namibia', code: 'NA', currency: 'Namibian Dollar', currencyCode: 'NAD' },
  { name: 'Mozambique', code: 'MZ', currency: 'Mozambican Metical', currencyCode: 'MZN' },
  { name: 'Madagascar', code: 'MG', currency: 'Malagasy Ariary', currencyCode: 'MGA' },
  { name: 'Mauritius', code: 'MU', currency: 'Mauritian Rupee', currencyCode: 'MUR' },
  { name: 'Seychelles', code: 'SC', currency: 'Seychellois Rupee', currencyCode: 'SCR' },
  { name: 'Cape Verde', code: 'CV', currency: 'Cape Verdean Escudo', currencyCode: 'CVE' },
  { name: 'Senegal', code: 'SN', currency: 'West African CFA Franc', currencyCode: 'XOF' },
  { name: 'Ivory Coast', code: 'CI', currency: 'West African CFA Franc', currencyCode: 'XOF' },
  { name: 'Cameroon', code: 'CM', currency: 'Central African CFA Franc', currencyCode: 'XAF' },
  { name: 'Tunisia', code: 'TN', currency: 'Tunisian Dinar', currencyCode: 'TND' },
  { name: 'Algeria', code: 'DZ', currency: 'Algerian Dinar', currencyCode: 'DZD' },
  { name: 'Libya', code: 'LY', currency: 'Libyan Dinar', currencyCode: 'LYD' },
  { name: 'Ecuador', code: 'EC', currency: 'US Dollar', currencyCode: 'USD' },
  { name: 'Bolivia', code: 'BO', currency: 'Bolivian Boliviano', currencyCode: 'BOB' },
  { name: 'Paraguay', code: 'PY', currency: 'Paraguayan Guaraní', currencyCode: 'PYG' },
  { name: 'Uruguay', code: 'UY', currency: 'Uruguayan Peso', currencyCode: 'UYU' },
  { name: 'Venezuela', code: 'VE', currency: 'Venezuelan Bolívar', currencyCode: 'VES' },
  { name: 'Guyana', code: 'GY', currency: 'Guyanese Dollar', currencyCode: 'GYD' },
  { name: 'Suriname', code: 'SR', currency: 'Surinamese Dollar', currencyCode: 'SRD' },
  { name: 'Trinidad and Tobago', code: 'TT', currency: 'Trinidad and Tobago Dollar', currencyCode: 'TTD' },
  { name: 'Barbados', code: 'BB', currency: 'Barbadian Dollar', currencyCode: 'BBD' },
  { name: 'Haiti', code: 'HT', currency: 'Haitian Gourde', currencyCode: 'HTG' },
];
